// Generated by CoffeeScript 1.10.0
(function() {
  var log, quote;

  quote = function(str) {
    if (str) {
      return "'" + str + "'";
    } else {
      return str;
    }
  };

  log = function(obj, group, msg) {
    console.log((quote(obj.name) || '[unnamed]') + " " + msg + " in " + (quote(group.name) || '[unnamed group]'));
  };

  new Phaser.Game({
    width: 600,
    height: 150,
    state: {
      create: function() {
        var group, nestedGroup, sprite, text, world;
        world = this.world;
        world.onChildAdded.add(log, null, null, 'added');
        world.onChildRemoved.add(log, null, null, 'removed');
        world.onChildKilled.add(log, null, null, 'killed');
        world.onChildRevived.add(log, null, null, 'revived');
        text = this.add.text(0, 0, 'see console 👀', {
          fill: 'white',
          font: '100px cursive'
        });
        group = this.add.group(world, 'group');
        group.onChildAdded.add(log, null, null, 'added');
        group.onChildRemoved.add(log, null, null, 'removed');
        group.onChildKilled.add(log, null, null, 'killed');
        group.onChildRevived.add(log, null, null, 'revived');
        nestedGroup = group.add(this.add.group(null, 'nestedGroup'));
        sprite = this.add.sprite();
        sprite.name = 'sprite';
        group.add(sprite);
        sprite.kill();
        sprite.revive();
        group.remove(sprite);
      }
    }
  });

}).call(this);
